# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ModifyMakeup' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ModifyMakeup
   pod 'Masonry', '~> 1.1.0'
   pod 'AFNetworking', '~> 3.2.1'
   pod 'coobjc', '~> 1.1.3'
#   pod 'YYModel', '~> 1.0.4'
   pod 'YYKit', '~> 1.0.9'
   pod 'TZImagePickerController', '~> 3.2.0'
     
target 'ModifyMakeupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModifyMakeupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
