# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

# Pods for StrangeAcquaintances
target 'StrangeAcquaintances' do
  use_frameworks!

  pod 'SDWebImage', '~> 4.4.6'

  pod 'YYCache', '~> 1.0.4'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCache', '~> 1.0.4'
  pod 'YYImage', '~> 1.0.4'
  pod 'YYWebImage', '~> 1.0.5'
  pod 'YYText', '~> 1.0.7'
  pod 'YYKeyboardManager', '~> 1.0.1'
  pod 'YYDispatchQueuePool', '~> 1.0'
  pod 'YYCategories', '~> 1.0.4'
  pod 'YYAsyncLayer', '~> 1.0'
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveCocoa', '~> 8.0.2'
  pod 'Texture'
  pod 'MyLayout', '~> 1.6.1'
#  pod 'BeeHive', '~> 1.6.0'
  pod 'coobjc', '~> 1.1.3'

end

target 'StrangeAcquaintancesTests' do
  inherit! :search_paths

end

target 'StrangeAcquaintancesUITests' do
  inherit! :search_paths

end


