# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'RegionalSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'RxSwift', '~> 4.4.2'

  # Pods for RegionalSystem

  target 'RegionalSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RegionalSystemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
